# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'student.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1081, 803)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(780, 150, 72, 15))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(780, 200, 72, 15))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(780, 250, 72, 15))
        self.label_5.setObjectName("label_5")
        self.name_inpot = QtWidgets.QLineEdit(Form)
        self.name_inpot.setGeometry(QtCore.QRect(832, 90, 211, 31))
        self.name_inpot.setObjectName("name_inpot")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(780, 100, 72, 15))
        self.label_2.setObjectName("label_2")
        self.birth_inpot = QtWidgets.QLineEdit(Form)
        self.birth_inpot.setGeometry(QtCore.QRect(830, 240, 211, 31))
        self.birth_inpot.setObjectName("birth_inpot")
        self.quer_bot = QtWidgets.QPushButton(Form)
        self.quer_bot.setGeometry(QtCore.QRect(790, 700, 251, 71))
        self.quer_bot.setObjectName("quer_bot")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(780, 50, 72, 15))
        self.label.setObjectName("label")
        self.amend_bot = QtWidgets.QPushButton(Form)
        self.amend_bot.setGeometry(QtCore.QRect(570, 700, 191, 71))
        self.amend_bot.setObjectName("amend_bot")
        self.id_inpot = QtWidgets.QLineEdit(Form)
        self.id_inpot.setGeometry(QtCore.QRect(832, 40, 211, 31))
        self.id_inpot.setObjectName("id_inpot")
        self.infor_text = QtWidgets.QTextEdit(Form)
        self.infor_text.setGeometry(QtCore.QRect(780, 300, 261, 371))
        self.infor_text.setObjectName("infor_text")
        self.class_input = QtWidgets.QLineEdit(Form)
        self.class_input.setGeometry(QtCore.QRect(830, 190, 211, 31))
        self.class_input.setObjectName("class_input")
        self.sex_inpot = QtWidgets.QLineEdit(Form)
        self.sex_inpot.setGeometry(QtCore.QRect(830, 140, 211, 31))
        self.sex_inpot.setObjectName("sex_inpot")
        self.camare_bot = QtWidgets.QPushButton(Form)
        self.camare_bot.setGeometry(QtCore.QRect(370, 700, 171, 71))
        self.camare_bot.setObjectName("camare_bot")
        self.gather_bot = QtWidgets.QPushButton(Form)
        self.gather_bot.setGeometry(QtCore.QRect(120, 700, 221, 71))
        self.gather_bot.setObjectName("gather_bot")
        self.title_01 = QtWidgets.QLabel(Form)
        self.title_01.setGeometry(QtCore.QRect(251, 20, 201, 20))
        self.title_01.setText("")
        self.title_01.setObjectName("title_01")
        self.previou_bot = QtWidgets.QPushButton(Form)
        self.previou_bot.setGeometry(QtCore.QRect(31, 700, 81, 71))
        self.previou_bot.setObjectName("previou_bot")
        self.voide_pr = QtWidgets.QLabel(Form)
        self.voide_pr.setGeometry(QtCore.QRect(41, 84, 691, 571))
        self.voide_pr.setText("")
        self.voide_pr.setObjectName("voide_pr")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "学号："))
        self.label_3.setText(_translate("Form", "性别："))
        self.label_4.setText(_translate("Form", "班级："))
        self.label_5.setText(_translate("Form", "生日："))
        self.label_2.setText(_translate("Form", "姓名："))
        self.quer_bot.setText(_translate("Form", "输入学号查询信息"))
        self.amend_bot.setText(_translate("Form", "录入信息"))
        self.camare_bot.setText(_translate("Form", "开始采集"))
        self.gather_bot.setText(_translate("Form", "打开相机"))
        self.previou_bot.setText(_translate("Form", "上一页"))
